namespace AIKeyMouse.CodeGen.CLI.Models.LLM;

/// <summary>
/// Response from an LLM provider
/// </summary>
public class LlmResponse
{
    /// <summary>
    /// Generated text content
    /// </summary>
    public required string Content { get; set; }

    /// <summary>
    /// Model that generated the response
    /// </summary>
    public required string Model { get; set; }

    /// <summary>
    /// Provider name (groq, huggingface)
    /// </summary>
    public required string Provider { get; set; }

    /// <summary>
    /// Number of tokens in the prompt
    /// </summary>
    public int PromptTokens { get; set; }

    /// <summary>
    /// Number of tokens in the completion
    /// </summary>
    public int CompletionTokens { get; set; }

    /// <summary>
    /// Total tokens used
    /// </summary>
    public int TotalTokens => PromptTokens + CompletionTokens;

    /// <summary>
    /// Whether this was generated by a fallback provider
    /// </summary>
    public bool IsFallback { get; set; }

    /// <summary>
    /// Finish reason (completed, length, stop, etc.)
    /// </summary>
    public string? FinishReason { get; set; }
}
